### PR TITLE
Replaced deprecated apt tool with annotation processing API

### PR DESCRIPTION
**Pull request by dheid**
Since the apt tool is no longer supported in Java 8, I replaced the apt usage with the recommended classes according to the blog entry of Joseph D. Darcy: 

https://blogs.oracle.com/darcy/entry/an_apt_replacement

Since a lot of imports changed, I needed to optimize the imports later on. This leeds to a bunch of changes on mainly untouched files. Sorry about that! But at least we can use distribute me in the future!

### CODE REVIEW

**Comment by dvayanu** [comment]
Hi Daniel,
thank you very much for your pull request, this is awesome and a whole lot of work you put into it. Since the commits are rather huge, allow us please to spend some hours to review them, before we merge.
Thank you again, your effort is much appreciated!

**Comment by dheid** [comment]
Thank you, too! I fixed another major bug with combined service names please also review commit 0c02b69f7c7956c1d5b3ec77fce13c1f1073f94e

**Comment by dvayanu** [comment]
I've merged this pull request. I also raised the version string to 2.3.0 since the change is too serious for a minor update. In the next couple of days we will test the compatibility with other applications, you are invited to test too ,-)

**Comment by dvayanu** [comment]
'Funny' thing, after the merge the CI job stoped working: 
https://jenkins.opensource.anotheria.net/jenkins/view/DistributeMe/job/distributeme_ci/1014/console
I tried to upgrade JDK to latest Java 8 jdk, but it didn't help. Any ideas?

**Pull request merged**
